/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumini;
import java.awt.CardLayout;


/**
 *
 * @author piyush
 */
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());
    private AlumniPanel alumniPanel;
   private announcementpanel announcementsPanel;
   private eventpanel eventpanel;
   private jobpanel jobpanel;
   private faqpanel faqpanel;
   private userpanel userpanel;
    public Admin() {
        initComponents();
         announcementsPanel = new announcementpanel();
         
        mainContentPanel.add(announcementsPanel, "announcements");
        alumniPanel = new AlumniPanel(); // create instance of your panel
        mainContentPanel.add(alumniPanel, "alumni");
        eventpanel= new eventpanel();
    mainContentPanel.add(eventpanel, "eventpanel");
   
        jobpanel=new jobpanel();
        mainContentPanel.add(jobpanel, "jobpanel");
   
          faqpanel=new faqpanel();
        mainContentPanel.add(faqpanel, "faqpanel");
        userpanel=new userpanel();
        mainContentPanel.add(userpanel, "userpanel");
        
   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlumini = new javax.swing.JButton();
        btnAnnouncements = new javax.swing.JButton();
        btnEvents = new javax.swing.JButton();
        btnJobOpportunities = new javax.swing.JButton();
        btnFAQs = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAlumini.setText("Alumini");
        btnAlumini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluminiActionPerformed(evt);
            }
        });

        btnAnnouncements.setText("Announcements");
        btnAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnouncementsActionPerformed(evt);
            }
        });

        btnEvents.setText("Events");
        btnEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventsActionPerformed(evt);
            }
        });

        btnJobOpportunities.setText("Job Opportunities");
        btnJobOpportunities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobOpportunitiesActionPerformed(evt);
            }
        });

        btnFAQs.setText("FAQ");
        btnFAQs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFAQsActionPerformed(evt);
            }
        });

        btnUsers.setText("Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        jLabel1.setText("DATABASE CONTROLS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFAQs, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJobOpportunities, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumini, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlumini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnnouncements)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEvents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJobOpportunities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFAQs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsers)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        mainContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAluminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluminiActionPerformed
      CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();
      cardLayout.show(mainContentPanel, "alumni");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAluminiActionPerformed

    private void btnAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnouncementsActionPerformed
    CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();
    cardLayout.show(mainContentPanel, "announcements");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnnouncementsActionPerformed

    private void btnEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventsActionPerformed
     CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();
    cardLayout.show(mainContentPanel, "eventpanel");
  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventsActionPerformed

    private void btnJobOpportunitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobOpportunitiesActionPerformed

         CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();
    cardLayout.show(mainContentPanel, "jobpanel");
  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJobOpportunitiesActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed

           CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();
    cardLayout.show(mainContentPanel, "userpanel");
     // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnFAQsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFAQsActionPerformed
            CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();
    cardLayout.show(mainContentPanel, "faqpanel");
  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFAQsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumini;
    private javax.swing.JButton btnAnnouncements;
    private javax.swing.JButton btnEvents;
    private javax.swing.JButton btnFAQs;
    private javax.swing.JButton btnJobOpportunities;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContentPanel;
    // End of variables declaration//GEN-END:variables
}
