/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumini;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author piyush
 */
public class eventpanel extends javax.swing.JPanel {

    /**
     * Creates new form AlumniPanel
     */
    public eventpanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout());

        jLabel2.setText("SEARCH  FAQ:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1))
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "event_name", "event_date", "event_venue", "description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAdd)
                        .addGap(12, 12, 12)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     // TODO add your handling code here:
String searchText = txtSearch.getText().trim();

if (searchText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter an event name to search.");
    return;
}

try (Connection conn = dbconnection.getConnection()) {

    String sql = "SELECT * FROM events WHERE event_name LIKE ?";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setString(1, "%" + searchText + "%");  // partial search by event name

    ResultSet rs = ps.executeQuery();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear old rows

    while (rs.next()) {
        Object[] row = {
            rs.getInt("id"),
            rs.getString("event_name"),
            rs.getDate("event_date"),
            rs.getString("event_venue"),
            rs.getString("description")
        };
        model.addRow(row);
    }

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No matching events found.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error searching events: " + e.getMessage());
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String eventName = JOptionPane.showInputDialog(this, "Enter Event Name:");
if (eventName == null || eventName.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Event name is required.");
    return;
}

String eventDateStr = JOptionPane.showInputDialog(this, "Enter Event Date (YYYY-MM-DD):");
if (eventDateStr == null || eventDateStr.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Event date is required.");
    return;
}

// Convert to java.sql.Date
java.sql.Date eventDate;
try {
    eventDate = java.sql.Date.valueOf(eventDateStr);
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Invalid date format! Use YYYY-MM-DD");
    return;
}

String eventVenue = JOptionPane.showInputDialog(this, "Enter Event Venue:");
if (eventVenue == null || eventVenue.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Event venue is required.");
    return;
}

String description = JOptionPane.showInputDialog(this, "Enter Description:");
if (description == null || description.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Description is required.");
    return;
}

try (Connection conn = dbconnection.getConnection()) {

    String sql = "INSERT INTO events (event_name, event_date, event_venue, description) VALUES (?, ?, ?, ?)";
    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, eventName.trim());
    ps.setDate(2, eventDate);
    ps.setString(3, eventVenue.trim());
    ps.setString(4, description.trim());

    int rowsInserted = ps.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Event Added Successfully!");
        loadEventsData(); // refresh table
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error adding event: " + e.getMessage());
}

    }//GEN-LAST:event_btnAddActionPerformed
public void loadEventsData() {
    try (Connection conn = dbconnection.getConnection()) {

        String sql = "SELECT * FROM events";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id"),
                rs.getString("event_name"),
                rs.getDate("event_date"),
                rs.getString("event_venue"),
                rs.getString("description")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading events: " + e.getMessage());
    }
}


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to edit.");
    return;
}

// Get values from table
int eventId = (int) jTable1.getValueAt(selectedRow, 0);
String currentName = (String) jTable1.getValueAt(selectedRow, 1);
java.sql.Date currentDate = (java.sql.Date) jTable1.getValueAt(selectedRow, 2);
String currentVenue = (String) jTable1.getValueAt(selectedRow, 3);
String currentDescription = (String) jTable1.getValueAt(selectedRow, 4);

// Ask for new values
String newName = JOptionPane.showInputDialog(this, "Edit Event Name:", currentName);
if (newName == null) return;

String newDateStr = JOptionPane.showInputDialog(this, "Edit Event Date (YYYY-MM-DD):", currentDate.toString());
if (newDateStr == null) return;

String newVenue = JOptionPane.showInputDialog(this, "Edit Event Venue:", currentVenue);
if (newVenue == null) return;

String newDescription = JOptionPane.showInputDialog(this, "Edit Description:", currentDescription);
if (newDescription == null) return;

try (Connection conn = dbconnection.getConnection()) {

    String sql = "UPDATE events SET event_name = ?, event_date = ?, event_venue = ?, description = ? WHERE id = ?";
    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, newName.trim());
    ps.setDate(2, java.sql.Date.valueOf(newDateStr.trim())); // Convert string to SQL date
    ps.setString(3, newVenue.trim());
    ps.setString(4, newDescription.trim());
    ps.setInt(5, eventId);

    int rowsUpdated = ps.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(this, "Event Updated Successfully!");
        loadEventsData();  // Refresh table
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error updating event: " + e.getMessage());
}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    return;
}

// Get ID and Event Name from selected row
int eventId = (int) jTable1.getValueAt(selectedRow, 0);
String selectedEventName = (String) jTable1.getValueAt(selectedRow, 1);

// Confirmation dialog
int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete event: \"" + selectedEventName + "\"?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return; // User clicked No
}

try (Connection conn = dbconnection.getConnection()) {

    String sql = "DELETE FROM events WHERE id = ?";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setInt(1, eventId);

    int rowsDeleted = ps.executeUpdate();

    if (rowsDeleted > 0) {
        JOptionPane.showMessageDialog(this, "Event deleted successfully!");
        loadEventsData(); // Refresh table
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error deleting event: " + e.getMessage());
}
      // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       loadEventsData();
        JOptionPane.showMessageDialog(this, "Table refreshed successfully!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
