/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumini;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author piyush
 */
public class faqpanel extends javax.swing.JPanel {

    /**
     * Creates new form AlumniPanel
     */
    public faqpanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout());

        jLabel2.setText("SEARCH  EVENTS:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1))
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Question", "Answer", "Keywords"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAdd)
                        .addGap(12, 12, 12)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     // TODO add your handling code here:
String searchText = txtSearch.getText().trim();

if (searchText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter a keyword or question to search.");
    return;
}

try (Connection conn = dbconnection.getConnection()) {

    String sql = "SELECT * FROM faqs WHERE question LIKE ? OR answer LIKE ? OR keywords LIKE ?";
    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, "%" + searchText + "%");
    ps.setString(2, "%" + searchText + "%");
    ps.setString(3, "%" + searchText + "%");

    ResultSet rs = ps.executeQuery();

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);  // clear previous rows

    while (rs.next()) {
        Object[] row = {
            rs.getInt("faq_id"),
            rs.getString("question"),
            rs.getString("answer"),
            rs.getString("keywords")
        };
        model.addRow(row);
    }

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No matching FAQs found.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error searching FAQs: " + e.getMessage());
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    String question = JOptionPane.showInputDialog(this, "Enter Question:");
if (question == null || question.trim().isEmpty()) return;

String answer = JOptionPane.showInputDialog(this, "Enter Answer:");
if (answer == null || answer.trim().isEmpty()) return;

String keywords = JOptionPane.showInputDialog(this, "Enter Keywords (comma separated):");
if (keywords == null || keywords.trim().isEmpty()) return;

try (Connection conn = dbconnection.getConnection()) {

    String sql = "INSERT INTO faqs (question, answer, keywqrds) VALUES (?, ?, ?)";
    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, question.trim());
    ps.setString(2, answer.trim());
    ps.setString(3, keywords.trim());

    int rows = ps.executeUpdate();

    if (rows > 0) {
        JOptionPane.showMessageDialog(this, "FAQ Added Successfully!");
        loadFaqData();
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error adding FAQ: " + e.getMessage());
}

    }//GEN-LAST:event_btnAddActionPerformed
public void loadFaqData() {
    try (Connection conn = dbconnection.getConnection()) {

        String sql = "SELECT * FROM faqs";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            Object[] row = {
                rs.getInt("faq_id"),
                rs.getString("question"),
                rs.getString("answer"),
                rs.getString("keywords")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading FAQs: " + e.getMessage());
    }
}


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int selectedRow = jTable1.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to edit.");
    return;
}

int faqId = (int) jTable1.getValueAt(selectedRow, 0);
String currentQ = (String) jTable1.getValueAt(selectedRow, 1);
String currentA = (String) jTable1.getValueAt(selectedRow, 2);
String currentK = (String) jTable1.getValueAt(selectedRow, 3);

// Ask new values
String newQ = JOptionPane.showInputDialog(this, "Edit Question:", currentQ);
if (newQ == null) return;

String newA = JOptionPane.showInputDialog(this, "Edit Answer:", currentA);
if (newA == null) return;

String newK = JOptionPane.showInputDialog(this, "Edit Keywords:", currentK);
if (newK == null) return;

try (Connection conn = dbconnection.getConnection()) {

    String sql = "UPDATE faqs SET question = ?, answer = ?, keywqrds = ? WHERE faq_id = ?";
    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, newQ.trim());
    ps.setString(2, newA.trim());
    ps.setString(3, newK.trim());
    ps.setInt(4, faqId);

    int rows = ps.executeUpdate();

    if (rows > 0) {
        JOptionPane.showMessageDialog(this, "FAQ updated successfully!");
        loadFaqData();
    }

    } catch (Exception e) {
     JOptionPane.showMessageDialog(this, "Error updating FAQ: " + e.getMessage());
     }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    return;
}

// Get ID and Question from selected row
int faqId = (int) jTable1.getValueAt(selectedRow, 0);
String selectedQuestion = (String) jTable1.getValueAt(selectedRow, 1);

// Confirmation
int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete FAQ: \"" + selectedQuestion + "\"?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) return;

try (Connection conn = dbconnection.getConnection()) {

    String sql = "DELETE FROM faqs WHERE faq_id = ?";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setInt(1, faqId);

    int rowsDeleted = ps.executeUpdate();

    if (rowsDeleted > 0) {
        JOptionPane.showMessageDialog(this, "FAQ deleted successfully!");
        loadFaqData(); // Refresh table
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error deleting FAQ: " + e.getMessage());
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       loadFaqData();
        JOptionPane.showMessageDialog(this, "Table refreshed successfully!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
