/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumini;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author piyush
 */
public class jobpanel extends javax.swing.JPanel {

    /**
     * Creates new form AlumniPanel
     */
    public jobpanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout());

        jLabel2.setText("SEARCH  JOBS:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1))
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Job Id", "Title", "Company", "Location", "Type", "Description", "Posted_date", "Posted_by"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAdd)
                        .addGap(12, 12, 12)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     // TODO add your handling code here:
String searchText = txtSearch.getText().trim();

if (searchText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter a job title to search.");
    return;
}

try (Connection conn = dbconnection.getConnection()) {

    String sql = "SELECT * FROM job_opportunities WHERE title LIKE ?";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setString(1, "%" + searchText + "%");  // partial match on job title

    ResultSet rs = ps.executeQuery();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear old rows

    while (rs.next()) {
        Object[] row = {
            rs.getInt("job_id"),
            rs.getString("title"),
            rs.getString("company"),
            rs.getString("location"),
            rs.getString("type"),
            rs.getString("department"),
            rs.getString("description"),
            rs.getDate("posted_date"),
            rs.getString("posted_by")
        };
        model.addRow(row);
    }

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No matching job opportunities found.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error searching job opportunities: " + e.getMessage());
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
 String title = JOptionPane.showInputDialog(this, "Enter Job Title:");
if (title == null || title.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Job title is required.");
    return;
}

String company = JOptionPane.showInputDialog(this, "Enter Company:");
if (company == null || company.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Company is required.");
    return;
}

String location = JOptionPane.showInputDialog(this, "Enter Job Location:");
if (location == null || location.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Location is required.");
    return;
}

String type = JOptionPane.showInputDialog(this, "Enter Job Type (Full-time, Part-time, Internship...):");
if (type == null || type.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Job type is required.");
    return;
}

String department = JOptionPane.showInputDialog(this, "Enter Department:");
if (department == null || department.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Department is required.");
    return;
}

String description = JOptionPane.showInputDialog(this, "Enter Job Description:");
if (description == null || description.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Description is required.");
    return;
}

String postedBy = JOptionPane.showInputDialog(this, "Posted By:");
if (postedBy == null || postedBy.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Posted By is required.");
    return;
}

// Auto-set current date
java.sql.Date postedDate = new java.sql.Date(System.currentTimeMillis());

try (Connection conn = dbconnection.getConnection()) {

    String sql = "INSERT INTO job_opportunities (title, company, location, type, department, description, posted_date, posted_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, title.trim());
    ps.setString(2, company.trim());
    ps.setString(3, location.trim());
    ps.setString(4, type.trim());
    ps.setString(5, department.trim());
    ps.setString(6, description.trim());
    ps.setDate(7, postedDate);
    ps.setString(8, postedBy.trim());

    int rowsInserted = ps.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Job Opportunity Added Successfully!");
        loadJobData(); // refresh table
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error adding job opportunity: " + e.getMessage());
}
   

    }//GEN-LAST:event_btnAddActionPerformed

   public void loadJobData() {
    try (Connection conn = dbconnection.getConnection()) {

        String sql = "SELECT * FROM job_opportunities";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear table

        while (rs.next()) {
            Object[] row = {
                rs.getInt("job_id"),
                rs.getString("title"),
                rs.getString("company"),
                rs.getString("location"),
                rs.getString("type"),
                rs.getString("department"),
                rs.getString("description"),
                rs.getDate("posted_date"),
                rs.getString("posted_by")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading job opportunities: " + e.getMessage());
    }
}
   

 


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to edit.");
        return;
    }

    // Get existing values from the table
    int jobId = (int) jTable1.getValueAt(selectedRow, 0);       // id
    String currentTitle = (String) jTable1.getValueAt(selectedRow, 1); // job_title
    String currentCompany = (String) jTable1.getValueAt(selectedRow, 2); // company
    String currentLocation = (String) jTable1.getValueAt(selectedRow, 3); // location
    String currentSalary = (String) jTable1.getValueAt(selectedRow, 4); // salary
    String currentDescription = (String) jTable1.getValueAt(selectedRow, 5); // description

    // Ask user for updated values
    String newTitle = JOptionPane.showInputDialog(this, "Edit Job Title:", currentTitle);
    if (newTitle == null) return;

    String newCompany = JOptionPane.showInputDialog(this, "Edit Company Name:", currentCompany);
    if (newCompany == null) return;

    String newLocation = JOptionPane.showInputDialog(this, "Edit Job Location:", currentLocation);
    if (newLocation == null) return;

    String newSalary = JOptionPane.showInputDialog(this, "Edit Salary:", currentSalary);
    if (newSalary == null) return;

    String newDescription = JOptionPane.showInputDialog(this, "Edit Job Description:", currentDescription);
    if (newDescription == null) return;

    try (Connection conn = dbconnection.getConnection()) {

        String sql = "UPDATE job_opportunities SET job_title = ?, company = ?, location = ?, salary = ?, description = ? WHERE id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, newTitle.trim());
        ps.setString(2, newCompany.trim());
        ps.setString(3, newLocation.trim());
        ps.setString(4, newSalary.trim());
        ps.setString(5, newDescription.trim());
        ps.setInt(6, jobId);

        int rowsUpdated = ps.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Job Updated Successfully!");
            loadJobData();   // refresh table
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating job: " + e.getMessage());
    }


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    return;
}

// Get ID and Job Title from selected row
int jobId = (int) jTable1.getValueAt(selectedRow, 0);
String selectedJobTitle = (String) jTable1.getValueAt(selectedRow, 1);

// Confirmation dialog
int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete job: \"" + selectedJobTitle + "\"?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return; // User clicked No
}

try (Connection conn = dbconnection.getConnection()) {

    String sql = "DELETE FROM job_opportunities WHERE id = ?";
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setInt(1, jobId);

    int rowsDeleted = ps.executeUpdate();

    if (rowsDeleted > 0) {
        JOptionPane.showMessageDialog(this, "Job deleted successfully!");
        loadJobData(); // Refresh table
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error deleting job: " + e.getMessage());
}
  // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       loadJobData();
        JOptionPane.showMessageDialog(this, "Table refreshed successfully!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
