/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumini;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author piyush
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("username");

        jLabel2.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

      String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();

    try (Connection conn = dbconnection.getConnection()) {

        boolean loggedIn = false;

        // 1️⃣ Check if Admin
        
        String adminQuery = "SELECT * FROM administrators WHERE username = ? AND password = ?";
        PreparedStatement psAdmin = conn.prepareStatement(adminQuery);
        psAdmin.setString(1, username);
        psAdmin.setString(2, password);
        ResultSet rsAdmin = psAdmin.executeQuery();

        if (rsAdmin.next()) {
            loggedIn = true;
            JOptionPane.showMessageDialog(this, "✅ Welcome Admin " + username + "!");
            
            // Open admin window
            Admin adminWindow = new Admin();
            adminWindow.setVisible(true); 
            adminWindow.pack();
            adminWindow.setLocationRelativeTo(null);
            this.dispose();
        }

        // 2️⃣ If not admin, check Alumni
        if (!loggedIn) {
            String alumniQuery = "SELECT * FROM alumni WHERE username = ? AND password = ?";
            PreparedStatement psAlumni = conn.prepareStatement(alumniQuery);
            psAlumni.setString(1, username);
            psAlumni.setString(2, password);
            ResultSet rsAlumni = psAlumni.executeQuery();

            if (rsAlumni.next()) {
                loggedIn = true;
                JOptionPane.showMessageDialog(this, "✅ Welcome Alumni " + rsAlumni.getString("name") + "!");
                
                // Open chat window for alumni
                chatinterface chatWindow = new chatinterface(username, "alumni");
                chatWindow.setVisible(true);
                chatWindow.pack();
                chatWindow.setLocationRelativeTo(null);
                this.dispose();
            }
        }

        // 3️⃣ If not alumni, check Normal User
        if (!loggedIn) {
            String userQuery = "SELECT * FROM users WHERE username = ? AND password = ?";
            PreparedStatement psUser = conn.prepareStatement(userQuery);
            psUser.setString(1, username);
            psUser.setString(2, password);
            ResultSet rsUser = psUser.executeQuery();

            if (rsUser.next()) {
                loggedIn = true;
                JOptionPane.showMessageDialog(this, "✅ Welcome " + rsUser.getString("name") + "!");
                
                // Open chat window for normal user
                chatinterface chatWindow = new chatinterface(username, "user");
                chatWindow.setVisible(true);
                chatWindow.pack();
                chatWindow.setLocationRelativeTo(null);
                this.dispose();
            }
        }

        // 4️⃣ If no match found
        if (!loggedIn) {
            JOptionPane.showMessageDialog(this, "❌ Invalid username or password.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "⚠️ Error: " + e.getMessage());
    }


    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
